In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Filtering all the AQI Databases from the last 5 years to only include Texas

In [ ]:
# 2025
df = pd.read_csv("/content/annual_aqi_by_county_2025.csv")
texasAQI_25 = df[df["State"] == "Texas"]
print(texasAQI_25.shape)
texasAQI_25.head(10)

(45, 18)

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
798,Texas,Atascosa,2025,341,259,82,0,0,0,0,92,61,35,0,0,0,341,0
799,Texas,Bell,2025,365,241,120,4,0,0,0,140,65,45,0,0,236,129,0
800,Texas,Bexar,2025,365,158,196,10,1,0,0,154,80,52,0,4,152,203,6
801,Texas,Bowie,2025,342,188,153,1,0,0,0,107,59,48,0,0,0,342,0
802,Texas,Brazoria,2025,365,295,62,8,0,0,0,143,71,35,0,11,326,28,0
803,Texas,Brazos,2025,340,233,107,0,0,0,0,78,57,40,0,0,0,340,0
804,Texas,Brewster,2025,364,272,91,0,1,0,0,164,64,43,0,0,307,57,0
805,Texas,Cameron,2025,365,109,248,8,0,0,0,139,76,57,0,0,50,315,0
806,Texas,Collin,2025,359,272,64,20,3,0,0,156,90,40,0,0,359,0,0
807,Texas,Culberson,2025,88,67,19,1,1,0,0,159,67,32,0,0,0,88,0

In [ ]:
# 2024
df = pd.read_csv("/content/annual_aqi_by_county_2024.csv")
texasAQI_24 = df[df["State"] == "Texas"]
print(texasAQI_24.shape)
texasAQI_24.head(10)

(45, 18)

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
808,Texas,Atascosa,2024,347,198,141,8,0,0,0,116,72,44,0,0,0,347,0
809,Texas,Bell,2024,366,226,135,5,0,0,0,129,70,46,0,0,224,142,0
810,Texas,Bexar,2024,366,174,170,20,2,0,0,199,87,52,0,3,139,221,3
811,Texas,Bowie,2024,360,189,171,0,0,0,0,97,62,49,0,0,0,360,0
812,Texas,Brazoria,2024,365,303,56,5,1,0,0,164,60,37,0,4,330,31,0
813,Texas,Brazos,2024,353,232,120,1,0,0,0,102,58,39,0,0,0,353,0
814,Texas,Brewster,2024,327,231,94,2,0,0,0,112,67,43,0,0,241,86,0
815,Texas,Cameron,2024,366,99,206,48,13,0,0,171,124,61,0,0,44,322,0
816,Texas,Collin,2024,365,283,71,8,3,0,0,161,77,40,0,0,365,0,0
817,Texas,Culberson,2024,111,99,12,0,0,0,0,88,52,26,0,0,0,111,0

In [ ]:
# 2023
df = pd.read_csv("/content/annual_aqi_by_county_2023.csv")
texasAQI_23 = df[df["State"] == "Texas"]
print(texasAQI_23.shape)
texasAQI_23.head(10)

(45, 18)

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
806,Texas,Atascosa,2023,330,210,120,0,0,0,0,86,64,42,0,0,0,330,0
807,Texas,Bell,2023,365,231,128,6,0,0,0,133,74,44,0,0,246,119,0
808,Texas,Bexar,2023,365,164,189,10,1,0,1,309,79,52,0,1,141,223,0
809,Texas,Bowie,2023,321,130,190,1,0,0,0,107,65,53,0,0,0,321,0
810,Texas,Brazoria,2023,365,301,47,16,1,0,0,156,67,36,0,7,336,22,0
811,Texas,Brazos,2023,348,233,115,0,0,0,0,79,60,39,0,0,0,348,0
812,Texas,Brewster,2023,359,262,96,1,0,0,0,101,58,43,0,0,228,131,0
813,Texas,Cameron,2023,365,161,198,6,0,0,0,141,77,54,0,0,103,262,0
814,Texas,Collin,2023,356,261,74,19,2,0,0,154,80,41,0,0,356,0,0
815,Texas,Culberson,2023,107,101,6,0,0,0,0,89,44,20,0,0,0,107,0

In [ ]:
# 2022
df = pd.read_csv("/content/annual_aqi_by_county_2022.csv")
texasAQI_22 = df[df["State"] == "Texas"]
print(texasAQI_22.shape)
texasAQI_22.head(10)

(45, 18)

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
806,Texas,Atascosa,2023,330,210,120,0,0,0,0,86,64,42,0,0,0,330,0
807,Texas,Bell,2023,365,231,128,6,0,0,0,133,74,44,0,0,246,119,0
808,Texas,Bexar,2023,365,164,189,10,1,0,1,309,79,52,0,1,141,223,0
809,Texas,Bowie,2023,321,130,190,1,0,0,0,107,65,53,0,0,0,321,0
810,Texas,Brazoria,2023,365,301,47,16,1,0,0,156,67,36,0,7,336,22,0
811,Texas,Brazos,2023,348,233,115,0,0,0,0,79,60,39,0,0,0,348,0
812,Texas,Brewster,2023,359,262,96,1,0,0,0,101,58,43,0,0,228,131,0
813,Texas,Cameron,2023,365,161,198,6,0,0,0,141,77,54,0,0,103,262,0
814,Texas,Collin,2023,356,261,74,19,2,0,0,154,80,41,0,0,356,0,0
815,Texas,Culberson,2023,107,101,6,0,0,0,0,89,44,20,0,0,0,107,0

In [ ]:
# 2021
df = pd.read_csv("/content/annual_aqi_by_county_2021.csv")
texasAQI_21 = df[df["State"] == "Texas"]
print(texasAQI_21.shape)
texasAQI_21.head(10)

(45, 18)

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
806,Texas,Atascosa,2023,330,210,120,0,0,0,0,86,64,42,0,0,0,330,0
807,Texas,Bell,2023,365,231,128,6,0,0,0,133,74,44,0,0,246,119,0
808,Texas,Bexar,2023,365,164,189,10,1,0,1,309,79,52,0,1,141,223,0
809,Texas,Bowie,2023,321,130,190,1,0,0,0,107,65,53,0,0,0,321,0
810,Texas,Brazoria,2023,365,301,47,16,1,0,0,156,67,36,0,7,336,22,0
811,Texas,Brazos,2023,348,233,115,0,0,0,0,79,60,39,0,0,0,348,0
812,Texas,Brewster,2023,359,262,96,1,0,0,0,101,58,43,0,0,228,131,0
813,Texas,Cameron,2023,365,161,198,6,0,0,0,141,77,54,0,0,103,262,0
814,Texas,Collin,2023,356,261,74,19,2,0,0,154,80,41,0,0,356,0,0
815,Texas,Culberson,2023,107,101,6,0,0,0,0,89,44,20,0,0,0,107,0

Combining seperate years of AQI data into one dataset with all 5 years

In [ ]:
# code for combining aqi data
pd.concat([texas])

Filtering all the Temperature data from the last 5 years to only include Texas

In [ ]:
Temperature = pd.read_csv("/content/avg_temp_2021_2025.csv", header=2, skiprows=[2])
Temperature.rename(columns={"Name": "County"}, inplace=True)
print(Temperature.shape)
Temperature.head(10)

(254, 7)

,ID,County,State,Value,Anomaly (1901-2000 base period),Rank,1901-2000 Mean
0,TX-001,Anderson County,Texas,67.2,1.8,126,65.4
1,TX-003,Andrews County,Texas,64.9,3.0,127,61.9
2,TX-005,Angelina County,Texas,68.5,2.5,127,66.1
3,TX-007,Aransas County,Texas,73.7,3.3,127,70.3
4,TX-009,Archer County,Texas,65.9,2.4,127,63.4
5,TX-011,Armstrong County,Texas,61.1,3.2,127,57.9
6,TX-013,Atascosa County,Texas,72.2,2.4,127,69.8
7,TX-015,Austin County,Texas,71.6,3.7,127,67.9
8,TX-017,Bailey County,Texas,59.7,2.7,127,57.0
9,TX-019,Bandera County,Texas,68.8,2.7,127,66.1

Filtering all the Rainfall data to only include Texas

In [ ]:
Rainfall = pd.read_csv("/content/avg_rain_2021_2025.csv", header=2, skiprows=[2])
Rainfall.rename(columns={"Name": "County"}, inplace=True)
print(Rainfall.shape)
Rainfall.head(10)

(254, 9)

,ID,County,State,Value,Anomaly (1901-2000 base period),Rank,1901-2000 Mean,Pctavg,Percent of Average
0,TX-001,Anderson County,Texas,227.33,19.94,106,207.39,109.6,NaN
1,TX-003,Andrews County,Texas,48.52,-25.36,3,73.88,65.7,NaN
2,TX-005,Angelina County,Texas,260.54,17.89,92,242.65,107.4,NaN
3,TX-007,Aransas County,Texas,162.20,-6.36,53,168.56,96.2,NaN
4,TX-009,Archer County,Texas,140.27,1.49,67,138.78,101.1,NaN
5,TX-011,Armstrong County,Texas,99.13,-5.58,42,104.71,94.7,NaN
6,TX-013,Atascosa County,Texas,107.48,-25.78,6,133.26,80.7,NaN
7,TX-015,Austin County,Texas,193.85,-11.61,34,205.46,94.4,NaN
8,TX-017,Bailey County,Texas,82.03,-5.69,36,87.72,93.5,NaN
9,TX-019,Bandera County,Texas,113.39,-35.99,7,149.38,75.9,NaN

Merging the datasets together

In [ ]:
Temperature['County'] = Temperature['County'].str.strip()
Temperature['County'] = Temperature['County'].str.strip()
merged_df = pd.merge(texasAQI_25, Temperature, on = 'County', how = 'inner')
print(merged_df.shape)
print(merged_df.columns)
merged_df.head()

(0, 24)
Index(['State_x', 'County', 'Year', 'Days with AQI', 'Good Days',
       'Moderate Days', 'Unhealthy for Sensitive Groups Days',
       'Unhealthy Days', 'Very Unhealthy Days', 'Hazardous Days', 'Max AQI',
       '90th Percentile AQI', 'Median AQI', 'Days CO', 'Days NO2',
       'Days Ozone', 'Days PM2.5', 'Days PM10', 'ID', 'State_y', 'Value',
       'Anomaly (1901-2000 base period)', 'Rank', '1901-2000 Mean'],
      dtype='object')

Empty DataFrame
Columns: [State_x, County, Year, Days with AQI, Good Days, Moderate Days, Unhealthy for Sensitive Groups Days, Unhealthy Days, Very Unhealthy Days, Hazardous Days, Max AQI, 90th Percentile AQI, Median AQI, Days CO, Days NO2, Days Ozone, Days PM2.5, Days PM10, ID, State_y, Value, Anomaly (1901-2000 base period), Rank, 1901-2000 Mean]
Index: []

[0 rows x 24 columns]

Keeping only relevant features (after combining all the datasets together)

In [ ]:
keep = []