In [ ]:
#pip install numpy pandas matplotlib seaborn scikit-learn openpyxl beautifulsoup4

KeyboardInterrupt:

In [2]:
import pandas as pd
tree_equity = pd.read_csv('tx_tes.csv')
tree_equity.head()

,GEOID,place,state,state_abbr,county,ua_name,ua_pop,congressio,cbg_pop,acs_pop,...,_veg1200,_tot1200,_bld1500,_veg1500,_tot1500,_bld1800,_veg1800,_tot1800,rank,rankgrpsz
0,480019505001,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,692.0,981.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17,24
1,480019505002,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,470.0,539.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24
2,480019505003,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,1915.0,1320.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18,24
3,480019505004,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,1016.0,1396.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24
4,480019506001,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,1473.0,1439.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24

In [4]:
tree_equity.drop(columns = ['linguistic', 'lingnorm'], inplace = True)
tree_equity.head()

,GEOID,place,state,state_abbr,county,ua_name,ua_pop,congressio,cbg_pop,acs_pop,...,_veg1200,_tot1200,_bld1500,_veg1500,_tot1500,_bld1800,_veg1800,_tot1800,rank,rankgrpsz
0,480019505001,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,692.0,981.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17,24
1,480019505002,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,470.0,539.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24
2,480019505003,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,1915.0,1320.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18,24
3,480019505004,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,1016.0,1396.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24
4,480019506001,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,1473.0,1439.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24

In [5]:
tree_equity.drop(columns = ['pctpoc', 'pctpov', 'unemplrate', 'dep_ratio', 'temp_diff'], inplace = True)
tree_equity.head()

,GEOID,place,state,state_abbr,county,ua_name,ua_pop,congressio,cbg_pop,acs_pop,...,_veg1200,_tot1200,_bld1500,_veg1500,_tot1500,_bld1800,_veg1800,_tot1800,rank,rankgrpsz
0,480019505001,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,692.0,981.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17,24
1,480019505002,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,470.0,539.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24
2,480019505003,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,1915.0,1320.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18,24
3,480019505004,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,1016.0,1396.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24
4,480019506001,Palestine,Texas,TX,Anderson County,"Palestine, TX",28558.0,TX Congressional District 5,1473.0,1439.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24

In [7]:
tree_equity.drop(columns = ['ua_pop', 'cbg_pop', 'acs_pop'], inplace = True)

In [8]:
downloadable = tree_equity.to_csv('tx_tes_cleaned.csv', index = False)

In [6]:
tree_equity = pd.read_csv('tx_tes_cleaned.csv')
tree_equity.drop(columns = ['child_perc', 'seniorperc'], inplace = True)
tree_equity.head()

,GEOID,place,state,state_abbr,county,ua_name,congressio,land_area,biome,cnpysource,...,_veg1200,_tot1200,_bld1500,_veg1500,_tot1500,_bld1800,_veg1800,_tot1800,rank,rankgrpsz
0,480019505001,Palestine,Texas,TX,Anderson County,"Palestine, TX",TX Congressional District 5,1.2827,Forest,Google,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17,24
1,480019505002,Palestine,Texas,TX,Anderson County,"Palestine, TX",TX Congressional District 5,2.1241,Forest,Google,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24
2,480019505003,Palestine,Texas,TX,Anderson County,"Palestine, TX",TX Congressional District 5,2.5378,Forest,Google,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18,24
3,480019505004,Palestine,Texas,TX,Anderson County,"Palestine, TX",TX Congressional District 5,3.2225,Forest,Google,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24
4,480019506001,Palestine,Texas,TX,Anderson County,"Palestine, TX",TX Congressional District 5,2.7991,Forest,Google,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,24

In [7]:
tree_equity.drop(columns = ['cnpysource'], inplace = True)

In [8]:
tree_equity.to_csv('tx_tes_cleaned_v2.csv', index = False)